name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ourstudio.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run:
        docker build . -t ourstudio.azurecr.io/ourstudiose/viruskoll:${{ github.sha }}
        docker push ourstudio.azurecr.io/ourstudiose/viruskoll:${{ github.sha }}
