name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run:
        docker build . -t ${{ secrets.REGISTRY }}/ourstudiose/viruskoll:${{ github.sha }}
        docker push ${{ secrets.REGISTRY }}/ourstudiose/viruskoll:${{ github.sha }}
